version: "3.8"

services:
  whatsapp-bot:
    build: . 
    container_name: umap_whatsapp_bot
    restart: unless-stopped
    ports:
      - "8001:3001"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
